---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: readthedocs-elasticsearch
  name: readthedocs-elasticsearch
spec:
  ports:
  - name: headless
    port: 9200
    targetPort: 9200
  selector:
    app: readthedocs-elasticsearch
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: readthedocs-elasticsearch
  name: readthedocs-elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: readthedocs-elasticsearch
    spec:
      containers:
      - env:
        - name: discovery.type
          value: single-node
        - name: http.host
          value: 0.0.0.0
        - name: xpack.security.enabled
          value: "false"
        image: elasticsearch:1.5
        name: readthedocs-elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
      restartPolicy: Always
