---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: readthedocs-postgres
  name: readthedocs-postgres
spec:
  ports:
  - port: 5432
    name: headless
    targetPort: 5432
  selector:
    app: readthedocs-postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: readthedocs-postgres
  labels:
    app: readthedocs-postgres
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: readthedocs-postgres
    spec:
      serviceAccountName: readthedocs
      imagePullSecrets:
      - name: babylonhealth-deploy-dev-pull-secret
      containers:
      - env:
        - name: POSTGRES_DB
          value: readthedocs
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: postgres
        image: postgres:latest
        name: readthedocs-postgres
