---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: readthedocs-redis
  name: readthedocs-redis
spec:
  ports:
  - port: 6379
    name: headless
    targetPort: 6379
  selector:
    app: readthedocs-redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: readthedocs-redis
  labels:
    app: readthedocs-redis
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: readthedocs-redis
    spec:
      serviceAccountName: readthedocs
      imagePullSecrets:
      - name: babylonhealth-deploy-dev-pull-secret
      containers:
      - image: redis
        name: readthedocs-redis
